apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-impress-api-live

bases:
  - ../../base

configMapGenerator:
  - name: location-service-v1
    behavior: merge
    literals:
      - MESSAGE=Current location is Madrid
