apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

configMapGenerator:
- name: location-service-v1
  behavior: merge
  literals:
  - MESSAGE=Current localtion is Montenegro
