apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: model-train-job-v1
    behavior: merge
    literals:
      - MESSAGE=Training job in Madrid

images:
  - name: bash
    newTag: "5.0.18"
