apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

configMapGenerator:
- name: document-service-v1
  behavior: merge
  literals:
  - MESSAGE=Hello from PRE-LIVE env
