apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service-v1
spec:
  template:
    spec:
      containers:
      - image: bash
        name: app
        volumeMounts:
        - name: command
          mountPath: /command.sh
          subPath: command.sh
        envFrom:
        - configMapRef:
            name: document-service-v1
        args: ["/bin/sh", "/command.sh"]
      volumes:
      - name: command 
        configMap:
          name: document-service-v1-command
      serviceAccountName: impress-api