apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: impress-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: impress-api
subjects:
  - kind: ServiceAccount
    name: impress-api