apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dmpkit-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dmpkit-api
subjects:
  - kind: ServiceAccount
    name: dmpkit-api