apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: impress-api-dev
  namespace: argo-cd
spec:
  generators:
  - git:
      repoURL: https://github.com/rinatsharipov/argocd-experiments
      revision: master
      directories:
      - path: impress-deployment/impress-api
      - path: impress-deployment/impress-api/*
      - path: impress-deployment/impress-api/base
        exclude: true
      - path: impress-deployment/impress-api/overlays
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}-dev'
      labels:
        app.kubernetes.io/part-of: my-impress-api
        app.kubernetes.io/environment: dev
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rinatsharipov/argocd-experiments
        targetRevision: master
        path: '{{ path }}/overlays/dev'
      destination:
        namespace: default
        server: https://kubernetes.default.svc
