apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: impress-api
  namespace: argo-cd
  labels:
    app.kubernetes.io/part-of: impress-api
spec:
  generators:
  - git:
      repoURL: https://github.com/rinatsharipov/argocd-experiments
      targetRevision: master
      directories:
        - impress-deployment/impress-api/*
  template:
    metadata:
      name: '{{ path.basename }}-dev'
      labels:
        app.kubernetes.io/part-of: impress-api
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rinatsharipov/argocd-experiments
        targetRevision: master
        path: {{ path }}/overlays/dev
      destination:
        namespace: default
        server: https://kubernetes.default.svc
