apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: impress-ml-live
  namespace: argo-cd
spec:
  generators:
  - git:
      repoURL: https://github.com/rinatsharipov/argocd-experiments
      revision: master
      directories:
      - path: impress-deployment/impress-ml
      - path: impress-deployment/impress-ml/*
      - path: impress-deployment/impress-ml/base
        exclude: true
      - path: impress-deployment/impress-ml/overlays
        exclude: true
  template:
    metadata:
      name: '{{path.basename}}-live'
      labels:
        app.kubernetes.io/part-of: impress-ml
        app.kubernetes.io/environment: live
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rinatsharipov/argocd-experiments
        targetRevision: master
        path: '{{ path }}/overlays/live'
      destination:
        namespace: default
        server: https://kubernetes.default.svc
